### ISSUE TITLE
--star_replace error

### ISSUE THREAD

**Issue by domgutier** [cdienem/StarTool#2]
Hello Chris, 
I tried to use the script but get the error below. This problem only happens with --replace_star as --replace works fine: 

[tiltall]$  python startool.py  particles.star --replace_star _rlnDefocusU=all_local.star:_rlnMicrographName,_rlnCoordinateX[1],_rlnCoordinateY[1] --writef test.star
### StarTool 1.3 (by Chris) ###
Starting StarTool in memory

Loading particles.star...
Percent: [####################] 100.0% Done...
Percent: [####################] 100.0% Done...

Only one input table read, using particles_data_

EXECUTE: --replace_star _rlnDefocusU=all_local.star:_rlnMicrographName,_rlnCoordinateX[1],_rlnCoordinateY[1]
Percent: [####################] 100.0% Done...
Percent: [####################] 100.0% Done...
Traceback (most recent call last):
  File "startool.py", line 357, in <module>
    stardb.star2db(file)
  File "/path/tiltall/STlib.py", line 117, in star2db
    self.makeTable(starfilename, name, labels, tuple(data))
  File "/path/tiltall/STlib.py", line 172, in makeTable
    labels[i] += " "+self.getType(field)
IndexError: list index out of range

**Comment by GavinR1** [comment]
Hi,

Were you able to solve this issue? I'm running into the exact same problem, want to replace the values for a column with those from a separate star file and getting index out of range.
